# Generated by Django 4.0.2 on 2022-02-28 18:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('databucket', '0002_rename_decription_files_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='compressed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='files',
            name='content_type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='files',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='files',
            name='file_storage_path',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='files',
            name='filename',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='files',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
